# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build-linux:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            # Runs a single command using the runners shell
            #- name: Run a one-line script
            #  run: echo Hello, world!

            - name: Setup premake
              # You may pin to the exact commit or the version.
              # uses: abel0b/setup-premake@8c96e76d62db4c5cbe7c16d7e5b80183534374c7
              uses: abel0b/setup-premake@v1

            # Runs a set of commands using the runners shell
            - name: Run a multi-line script
              run: |
                  premake5 gmake
                  make config=release

            - uses: actions/upload-artifact@v3
              with:
                  name: LinuxPluginx64
                  path: |
                      **/LuaPlugin*.so

    build-windows:
        # The type of runner that the job will run on
        runs-on: windows-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Add MSBuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Setup premake
              # You may pin to the exact commit or the version.
              # uses: abel0b/setup-premake@8c96e76d62db4c5cbe7c16d7e5b80183534374c7
              uses: abel0b/setup-premake@v1

            # Runs a set of commands using the runners shell
            - name: Run a multi-line script
              run: |
                  premaake5 vs2022
                  devenv VCMPLua.sln /Build

            - uses: actions/upload-artifact@v3
              with:
                  name: WindowsPluginx64
                  path: |
                      **/LuaPlugin*.dll
